package errorcheck

const (
	// ERROR_DEFAULT 디플트 값이 없는경우
	ERROR_DEFAULT = 00000
	// ERROR_DB_INCORRECT_SQL_SYNTAX SQL_SYNTAX
	ERROR_DB_INCORRECT_SQL_SYNTAX = 01000
	// ERROR_DB DB 에러
	ERROR_DB = 01001
	// ERROR_INPUT_VALUE 입력값 에러
	ERROR_INPUT_VALUE = 01002
	// ERROR_DUPLICATED_ID 중복 ID
	ERROR_DUPLICATED_ID = 10001
	// ERROR_DUPLICATED_EMAIL 중복 Email
	ERROR_DUPLICATED_EMAIL = 10002
	// ERROR_INCORRECT_PASSWORD 올바르지 않은 패스워드
	ERROR_INCORRECT_PASSWORD = 10003
	// ERROR_NOT_EXIST_ID 존재하지 않은 ID
	ERROR_NOT_EXIST_ID = 10004
	// ERROR_NOT_EXIST_EMAIL 존재하지 않은 이메일
	ERROR_NOT_EXIST_EMAIL = 10005
	// ERROR_INCORRECT_CODE 맞지않은 코드
	ERROR_INCORRECT_CODE = 10006
	// ERROR_INVALID_EMAIL_FORMAT Email format error
	ERROR_INVALID_EMAIL_FORMAT = 10007
	// ERROR_NOT_VERIFIED_EMAIL email verify error
	ERROR_NOT_VERIFIED_EMAIL = 10008
	// ERROR_MEMBERSHIP_REGISTRATION_FAILED 등록실패
	ERROR_MEMBERSHIP_REGISTRATION_FAILED = 10009
	// ERROR_INCORRECT_AUTHORIZATION 인증에러
	ERROR_INCORRECT_AUTHORIZATION = 10010
	// ERROR_PLEASE_TRY_AGAIN 재시도
	ERROR_PLEASE_TRY_AGAIN = 10011
	// ERROR_PASSWORD_IS_WEAK 패스워드 보안단계 에러
	ERROR_PASSWORD_IS_WEAK = 10012
	// ERROR_PLEASE_TRY_AGAIN_IN_FIVE_MINUTES 5분후에 재시도
	ERROR_PLEASE_TRY_AGAIN_IN_FIVE_MINUTES = 10013
	// ERROR_AUTH_LOCKED_USER 사용자 Lock상태
	ERROR_AUTH_LOCKED_USER = 10014
	// ERROR_MISSING_SCHOOL_INFORMATION 학교정보 없음
	ERROR_MISSING_SCHOOL_INFORMATION = 10015
	// ERROR_INCORRECT_VERIFICATION_CODE 맞지않은 verify code
	ERROR_INCORRECT_VERIFICATION_CODE = 10016
	// ERROR_INCORRECT_CONNECTION 유효한 연결이 아님
	ERROR_INCORRECT_CONNECTION = 20002
	// ERROR_NO_AUTHENTIFICATION 인증되지 않음
	ERROR_NO_AUTHENTIFICATION = 20004
	// ERROR_GRPC GPRC 에러
	ERROR_GRPC = 02000
)
